package model.pojo;
// Generated May 14, 2015 9:15:15 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Hikes generated by hbm2java
 */
public class Hikes  implements java.io.Serializable {


     private Integer id;
     private Users users;
     private String car;
     private String options;
     private int phone;
     private int rating;
     private int rides;
     private int seats;
     private int seatsLeft;
     private Date startDate;

    public Hikes() {
    }

    public Hikes(Users users, String car, String options, int phone, int rating, int rides, int seats, int seatsLeft, Date startDate) {
       this.users = users;
       this.car = car;
       this.options = options;
       this.phone = phone;
       this.rating = rating;
       this.rides = rides;
       this.seats = seats;
       this.seatsLeft = seatsLeft;
       this.startDate = startDate;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getCar() {
        return this.car;
    }
    
    public void setCar(String car) {
        this.car = car;
    }
    public String getOptions() {
        return this.options;
    }
    
    public void setOptions(String options) {
        this.options = options;
    }
    public int getPhone() {
        return this.phone;
    }
    
    public void setPhone(int phone) {
        this.phone = phone;
    }
    public int getRating() {
        return this.rating;
    }
    
    public void setRating(int rating) {
        this.rating = rating;
    }
    public int getRides() {
        return this.rides;
    }
    
    public void setRides(int rides) {
        this.rides = rides;
    }
    public int getSeats() {
        return this.seats;
    }
    
    public void setSeats(int seats) {
        this.seats = seats;
    }
    public int getSeatsLeft() {
        return this.seatsLeft;
    }
    
    public void setSeatsLeft(int seatsLeft) {
        this.seatsLeft = seatsLeft;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }




}


