package model.pojo;
// Generated May 14, 2015 9:15:15 AM by Hibernate Tools 3.6.0



/**
 * Hikers generated by hbm2java
 */
public class Hikers  implements java.io.Serializable {


     private Integer id;
     private Users users;
     private int hikeId;
     private int luggage;
     private int seats;

    public Hikers() {
    }

    public Hikers(Users users, int hikeId, int luggage, int seats) {
       this.users = users;
       this.hikeId = hikeId;
       this.luggage = luggage;
       this.seats = seats;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public int getHikeId() {
        return this.hikeId;
    }
    
    public void setHikeId(int hikeId) {
        this.hikeId = hikeId;
    }
    public int getLuggage() {
        return this.luggage;
    }
    
    public void setLuggage(int luggage) {
        this.luggage = luggage;
    }
    public int getSeats() {
        return this.seats;
    }
    
    public void setSeats(int seats) {
        this.seats = seats;
    }




}


