package model.pojo;
// Generated May 14, 2015 9:15:15 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Route generated by hbm2java
 */
public class Route  implements java.io.Serializable {


     private Integer id;
     private Date arrival;
     private Date departure;
     private String destination;
     private String intermediate;
     private String source;

    public Route() {
    }

    public Route(Date arrival, Date departure, String destination, String intermediate, String source) {
       this.arrival = arrival;
       this.departure = departure;
       this.destination = destination;
       this.intermediate = intermediate;
       this.source = source;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getArrival() {
        return this.arrival;
    }
    
    public void setArrival(Date arrival) {
        this.arrival = arrival;
    }
    public Date getDeparture() {
        return this.departure;
    }
    
    public void setDeparture(Date departure) {
        this.departure = departure;
    }
    public String getDestination() {
        return this.destination;
    }
    
    public void setDestination(String destination) {
        this.destination = destination;
    }
    public String getIntermediate() {
        return this.intermediate;
    }
    
    public void setIntermediate(String intermediate) {
        this.intermediate = intermediate;
    }
    public String getSource() {
        return this.source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }




}


