package model.pojo;
// Generated May 14, 2015 9:15:15 AM by Hibernate Tools 3.6.0



/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer id;
     private String email;
     private String password;
     private int gender;
     private byte[] hikesProviding;
     private byte[] hikesUsing;
     private String name;
     private Hikers hikers;
     private Hikes hikes;

    public Users() {
    }

	
    public Users(String email, int gender, String name, String Password) {
        this.email = email;
        this.gender = gender;
        this.name = name;
        this.password=Password;
    }
    public Users(String email, int gender, byte[] hikesProviding, byte[] hikesUsing, String name, Hikers hikers, Hikes hikes, String Password) {
       this.email = email;
       this.gender = gender;
       this.hikesProviding = hikesProviding;
       this.hikesUsing = hikesUsing;
       this.name = name;
       this.hikers = hikers;
       this.hikes = hikes;
       this.password=Password;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password=password;
    }
    
    public int getGender() {
        return this.gender;
    }
    
    public void setGender(int gender) {
        this.gender = gender;
    }
    public byte[] getHikesProviding() {
        return this.hikesProviding;
    }
    
    public void setHikesProviding(byte[] hikesProviding) {
        this.hikesProviding = hikesProviding;
    }
    public byte[] getHikesUsing() {
        return this.hikesUsing;
    }
    
    public void setHikesUsing(byte[] hikesUsing) {
        this.hikesUsing = hikesUsing;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Hikers getHikers() {
        return this.hikers;
    }
    
    public void setHikers(Hikers hikers) {
        this.hikers = hikers;
    }
    public Hikes getHikes() {
        return this.hikes;
    }
    
    public void setHikes(Hikes hikes) {
        this.hikes = hikes;
    }




}


